# docker-compose.yml
version: '3'

services:
  db:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_virtual_assistant
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data7
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d ai_virtual_assistant'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  virtual-assistant:
    image: quay.io/ecosystem-appeng/ai-virtual-assistant:1.1.0
    container_name: ai-virtual-assistant
    profiles:
      - deploy-va
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@host.containers.internal:5432/ai_virtual_assistant
      LLAMASTACK_URL: http://host.containers.internal:8321
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
