# Default values for vectordb-ingestion-monitor
namespace: llama-stack-rag

replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/openshift/tools
  tag: latest
  pullPolicy: IfNotPresent

monitor:
  name: ingestion-pipeline-monitor
  serviceAccount:
    create: true
    name: ingestion-pipeline-monitor
  rbac:
    create: true
    role:
      name: ingestion-pipeline-monitor
    roleBinding:
      name: ingestion-pipeline-monitor